Twitter bot to retweet tweets made by users when they tweet using some
hashtags.

* Configure

** Create a Twitter app

You first need to [[https://developer.twitter.com/en/apps][create a Twitter application]].

** Create a configuration file

For example, store this in =~/.retweet_config.edn=:

: {;; Twitter app configuration
:  :consumer-key      "example"
:  :consumer-secret   "example"
:  :user-token        "example"
:  :user-token-secret "example"
:  ;; Retweet configuration
:  :accounts          #{"bzg2"} 
:  :hashtags          #{"#freesoftware"}}

See =config_example.edn= in this repository.

When =user1= or =user2= tweets contain =#hashtag1= or =#hashtag1=, they will
be retweeted by your bot.

** Point =RETWEET_CONFIG= to this configuration file

The =RETWEET_CONFIG= environment variables should point to the
configuration file:

: RETWEET_CONFIG=/path/to/config.edn
 
You can set this in your =~/.profile= file.

* Deploy

** As a jar file

: ~$ lein uberjar
: ~$ java -jar target/retweet-0.3-standalone.jar

** As a docker container

Assuming you already created the =jar= file and your =RETWEET_CONFIG=
environment variable:

: docker build -t retweet_bot .
: docker run -it retweet_bot

* Contribute

Contributions are welcome as issues, questions or code.

* Support the Clojure ecosystem

If you like Clojure, please consider supporting Clojure developers by
donating to [[https://www.clojuriststogether.org][clojuriststogether.org]].  Thanks!

* License

© 2019 Bastien Guerry

Licensed under the EPL 2.0.
